{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "git-configmap-sync.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "git-configmap-sync.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "git-configmap-sync.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}