{{- if not .Values.gitClone.gitConfig.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git-configmap-sync.fullname" . }}
  labels:
    {{- include "git-configmap-sync.labels" . | nindent 4 }}
type: Opaque
data:
  git-username: {{ .Values.gitClone.gitConfig.credentials.username | b64enc | quote }}
  git-password: {{ .Values.gitClone.gitConfig.credentials.password | b64enc | quote }}
  git-private-ssh-key: {{ .Values.gitClone.gitConfig.credentials.privateSshKey | b64enc | quote }}
{{- end }}