apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-healthcheck.fullname" . }}
  labels:
    {{- include "http-healthcheck.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        include /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        access_log  off;
        sendfile        on;
        keepalive_timeout  65;

        server {
            server_name  _;
            listen 8080;
        
            location / {
                default_type application/json;
                return 200 '{"status":"ok","hostname":"$HOSTNAME"}';
            }
        }
    }
