apiVersion: v1
kind: Service
metadata:
  name: calert
  namespace: monitoring
  labels:
    app: calert
spec:
  selector:
    app: calert
  ports:
    - protocol: TCP
      port: 6000
      targetPort: http
      name: http
  type: ClusterIP # Use ClusterIP for internal cluster access