apiVersion: v1
kind: ConfigMap
metadata:
  name: calert-config
  namespace: monitoring
data:
  config.sample.toml: |
    # Basic application settings
    [app]
    address = "0.0.0.0:6000"
    server_timeout = "60s"
    enable_request_logs = true
    log = "debug" # Can be debug for verbose logging /info

    [providers."monitoring/team-sre-incident-hotline-gchat/incident-hotline-gchat"]
    type = "google_chat"
    endpoint = "https://chat.googleapis.com/v1/spaces/AAQA3y7HxE4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=mbp3OK27-OzA2fSbnv_Jl3Xi_JINkKsHv_GrnCVju2E" 
    max_idle_conns = 50
    timeout = "7s"
    template = "static/message.tmpl"
    thread_ttl = "12h"
    threaded_replies = true
    dry_run = false

    [providers."monitoring/team-sre-qa-calert/google-chat-sre-qa"]
    type = "google_chat"
    endpoint = "https://chat.googleapis.com/v1/spaces/AAQAaiGKxf0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=M606eaSjqo2D85SqyhOLWjI6xeY1vViyEvanpCwjxtk"
    max_idle_conns =  50 # Max idle connections in the HTTP Client.
    timeout = "7s" # Timeout for making requests to Provider.
    template = "static/message.tmpl" # Path to specify the message template path.
    thread_ttl = "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
    threaded_replies = true # Whether to send threaded replies or not.
    dry_run = false
