apiVersion: apps/v1
kind: Deployment
metadata:
  name: calert
  namespace: monitoring
  labels:
    app: calert
    # Add standard Kubernetes recommended labels (see Part 2)
    app.kubernetes.io/name: calert
    app.kubernetes.io/instance: calert-instance
    app.kubernetes.io/version: "v2.1.1" # Match your image version
    app.kubernetes.io/component: notification-webhook
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: kubectl # Or Helm, etc.
    # Add owner labels (see Part 2)
    kiwigrid_com_operated_by: "sre"
    kiwigrid_com_owned_by: "kiwigrid"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calert
  template:
    metadata:
      labels:
        app: calert
        app.kubernetes.io/name: calert
        app.kubernetes.io/instance: calert-instance
        # Add owner labels to the pod template as well for consistency
        kiwigrid_com_operated_by: your-team-name
        kiwigrid_com_owned_by: your-org-name
    spec:
      containers:
      - name: calert
        image: ghcr.io/mr-karan/calert:v2.1.1
        ports:
        - containerPort: 6000
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.sample.toml # --- IMPORTANT: Changed mountPath ---
          subPath: config.sample.toml       # --- IMPORTANT: Changed subPath ---
        env:
        - name: CALERT_PROVIDERS_YOUR_CHAT_ROOM__ENDPOINT
          valueFrom:
            secretKeyRef:
              name: calert-google-chat-webhook
              key: webhook-url
        resources:
          requests:
            cpu: "20m"
            memory: "48Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
        # --- START PSS COMPLIANCE ---
        securityContext:
          allowPrivilegeEscalation: false # Prevent privilege escalation
          capabilities:
            drop:
              - ALL # Drop all Linux capabilities
          runAsNonRoot: true # Ensure the container runs as a non-root user
          runAsUser: 65534 # <--- Added this line
          # It's good practice to set a specific UID if your image supports it,
          # otherwise, rely on the image's default non-root user.
          # For calert, the image likely already runs as non-root, so `runAsNonRoot: true` is enough.
          # If it still fails, you might need to find the UID calert's image uses and set runAsUser: <UID>
          seccompProfile:
            type: RuntimeDefault # Use the default seccomp profile from the container runtime
        # --- END PSS COMPLIANCE ---
      volumes:
      - name: config-volume
        configMap:
          name: calert-config