# local_calert_config.toml
[app]
address = "0.0.0.0:6000"
server_timeout = "60s"
enable_request_logs = true
log = "info"

[providers.my-chat-room] # Use 'my-chat-room' to match the env var name
type = "google_chat"
endpoint = "" # Will be overridden
max_idle_conns = 50
timeout = "7s"
thread_ttl = "12h"