apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-certs-ca-installer.fullname" . }}
  labels:
    {{- include "docker-certs-ca-installer.labels" . | nindent 4 }}
data:
  {{- range .Values.dockerCertsCaInstaller.caConfigs }}
  {{- $caConfig := . -}}
  {{- range $caConfig.hosts }}
  {{ printf "%s.crt" . }}: {{ $caConfig.x509Crt | quote }}
  {{- end }}
  {{- end }}
