{{- if .Values.psp.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "docker-certs-ca-installer.fullname" . }}-psp
  labels:
    {{- include "docker-certs-ca-installer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "docker-certs-ca-installer.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "docker-certs-ca-installer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}