apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-gchat-integration.fullname" . }}
  labels:
    {{- include "alertmanager-gchat-integration.labels" . | nindent 4 }}
data:
  notification-template-json.j2: {{ .Values.alertManagerGChatIntegration.notificationTemplateJsonJ2 | quote }}
