apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager-gchat-integration.fullname" . }}
  labels:
    {{- include "alertmanager-gchat-integration.labels" . | nindent 4 }}
    app.kubernetes.io/name: alertmanager-gchat-integration # Explicitly add if not covered by .labels
    kiwigrid_com_operated_by: sre # Your required label
    kiwigrid_com_owned_by: sre   # Your required label
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alertmanager-gchat-integration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "alertmanager-gchat-integration.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: alertmanager-gchat-integration # Explicitly add if not covered by .labels
        kiwigrid_com_operated_by: sre # Your required label
        kiwigrid_com_owned_by: sre   # Your required label
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertmanager-gchat-integration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true # Ensure the container runs as non-root
        runAsUser: 1000 # Specific user ID for this container
        seccompProfile:
          type: RuntimeDefault # Recommended for container-level seccomp
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          env:
            - name: PORT
              value: "8080"
            - name: CONFIG_FILE_LOCATION
              value: /opt/alertmanager-gchat-integration/secret/config.toml
          volumeMounts:
            - name: configmap-file
              mountPath: /opt/alertmanager-gchat-integration/cm
            - name: secret-file
              mountPath: /opt/alertmanager-gchat-integration/secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configmap-file
          configMap:
            name: {{ include "alertmanager-gchat-integration.fullname" . }}
        - name: secret-file
          secret:
            secretName: {{ include "alertmanager-gchat-integration.configTomlSecretName" . }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
