apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-url-playlist.fullname" . }}
  labels:
    {{- include "http-url-playlist.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.httpUrlPlaylist | toRawJson | quote }}
  nginx.conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;

    pid        /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        gzip  on;

        # Specifics around Non-Root user
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        # Server listening
        server {
            server_name  _;
            listen 8080;
        
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        }
    }