on:
  push:
    branches-ignore:
      - gh-pages

name: Lint

jobs:
  lint-helm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: azure/setup-helm@v1

    - name: Linting the charts
      run: make lint